name: CI
on:
  push:
    branches: [ "main" ]
env:
  MY_VARIABLE: This is a variable
  - name: Use my var
    run: echo ${{env.MY_VARIABLE}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hello Github Actions
        run: echo Hello, Github Actions!
      - name: Afficher la valeur du secret
        run: echo "La valeur de MY_SECRET est: ${{secrets.MY_SECRET}}"
      
