name: CI
on:
  push:
    branches: ["master"]

env:
  MY_VARIABLE: This is a variable
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hello Github Actions
        run: echo "Hello, Github Actions!"
      - name: Afficher la valeur du secret
        run: echo "La valeur du secret est : ${{secrets.MY_SECRET}}"
      - name: Use my var
        run: echo "${{env.MY_VARIABLE}}"
